### ISSUE TITLE
Routing not loaded by default

### ISSUE THREAD

**Issue by eFrane** [eFrane/TusBundle#73]
While the route loader is correctly registered the routes are not found by default unless something like

```yaml
tus_bundle:
  type: tus_bundle
  resource: .
```

is added to a using project's `routes.yaml`. This should either be mentioned in the docs or ideally be fixed.
